# Dataset Preparation

## Libraries

In [10]:
import cv2 
import matplotlib.pyplot as plt
import pandas as pd
import csv
import glob
import os

## Generating dataset

In [11]:
header = ["label"]
import cv2
import csv
import glob
 
header  =["label"]
for i in range(0,784):
    header.append("pixel"+str(i))
with open('dataset_a.csv', 'a') as f:
    writer = csv.writer(f)
    writer.writerow(header)

## Reading images and assigning labels

In [16]:
for label in range(135):
    dirList1 = glob.glob("C:/Users/madha/Downloads/Last Stage/data/"+str(label)+"/*.png")
    dirList2 = glob.glob("C:/Users/madha/Downloads/Last Stage/data/"+str(label)+"/*.jpg")
    dirList3 = glob.glob("C:/Users/madha/Downloads/Last Stage/data/"+str(label)+"/*.bmp")
    dirList = dirList1 + dirList2 + dirList3
    for img_path in dirList:
        im= cv2.imread(img_path)
        im_gray = cv2.cvtColor(im,cv2.COLOR_BGR2GRAY)
        #im = cv2.bitwise_not(im)
        if im is not None:
            _, thresh = cv2.threshold(im_gray, 127, 255, cv2.THRESH_BINARY) #remove background and convert image to binary
            #ctrs,_ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE) #contours and parent pt; return all boundary points
            contours, _ = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

            cnt = sorted(contours, key = lambda ctr:cv2.boundingRect(ctr)[0]) #bounding box/rect
            #for max dimension of rect/block
            w = int(28)
            h = int(28)
            maxi = 0
            for c in cnt:
                x, y, w, h = cv2.boundingRect(c)
                maxi = max(w*h, maxi)
                if maxi == w*h:
                    x_max = x
                    y_max = y
                    w_max = w
                    h_max = h
            #cropping accf to block
            im_crop = thresh[y_max: y_max + h + 10, x_max: x_max + w_max + 10]
            roi= cv2.resize(im_gray,(28,28), interpolation=cv2.INTER_AREA)
        
        data=[]
        data.append(label)
        rows, cols = roi.shape
        ## Add pixel one by one into data array
        for i in range(rows):
            for j in range(cols):
                k = roi[i,j]
                data.append(k)
        with open('dataset_new.csv', 'a') as f:
            writer = csv.writer(f)
            writer.writerow(data)

## Dataset Loading

In [18]:
import pandas as pd
from sklearn.utils import shuffle
data = pd.read_csv('dataset_new.csv')
data = shuffle(data)
data

,0,255,255.1,255.2,255.3,255.4,255.5,255.6,255.7,255.8,...,255.672,255.673,255.674,255.675,255.676,255.677,255.678,255.679,255.680,255.681
46052,33,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
85454,82,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
134699,126,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
18027,15,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
85612,83,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89889,91,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
18942,15,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
12024,14,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
121100,110,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
124336,111,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255