## Libraries

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_train = pd.read_csv("train_set_final.csv", index_col = False)
df_train.head()

,0,1,2,3,4,5,6,7,8,9,...,775,776,777,778,779,780,781,782,783,784
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
2,0,73,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
3,0,0,0,0,0,255,255,255,255,255,...,0,0,0,0,0,0,0,0,0,10
4,0,0,0,0,0,0,0,0,18,255,...,0,0,0,0,0,0,0,0,0,10

In [3]:
labels = df_train["784"]

In [4]:
df_train.drop(df_train.columns[[784]], axis = 1, inplace = True)
df_train.head()

,0,1,2,3,4,5,6,7,8,9,...,774,775,776,777,778,779,780,781,782,783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,73,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,255,255,255,255,255,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,18,255,...,0,0,0,0,0,0,0,0,0,0

In [5]:
labels

0       10
1       10
2       10
3       10
4       10
        ..
7096    12
7097    12
7098    12
7099    12
7100    12
Name: 784, Length: 7101, dtype: int64

## Libraries for CNN

In [7]:
pip install --upgrade tensorflow

Requirement already satisfied: tensorflow in c:\users\madha\anaconda3\lib\site-packages (2.7.0)
Requirement already satisfied: numpy>=1.14.5 in c:\users\madha\anaconda3\lib\site-packages (from tensorflow) (1.22.1)
Requirement already satisfied: keras-preprocessing>=1.1.1 in c:\users\madha\anaconda3\lib\site-packages (from tensorflow) (1.1.2)
Requirement already satisfied: gast<0.5.0,>=0.2.1 in c:\users\madha\anaconda3\lib\site-packages (from tensorflow) (0.3.3)
Requirement already satisfied: keras<2.8,>=2.7.0rc0 in c:\users\madha\anaconda3\lib\site-packages (from tensorflow) (2.7.0)
Requirement already satisfied: flatbuffers<3.0,>=1.12 in c:\users\madha\anaconda3\lib\site-packages (from tensorflow) (2.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\madha\anaconda3\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.21.0 in c:\users\madha\anaconda3\lib\site-packages (from tensorflow) (0.23.1)
Requirement already satisfied: google-pasta>=0.1.1 in c:\users\madha\anaconda3\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\madha\anaconda3\lib\site-packages (from tensorflow) (1.12.1)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\madha\anaconda3\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: h5py>=2.9.0 in c:\users\madha\anaconda3\lib\site-packages (from tensorflow) (2.10.0)
Requirement already satisfied: absl-py>=0.4.0 in c:\users\madha\anaconda3\lib\site-packages (from tensorflow) (1.0.0)
Requirement already satisfied: protobuf>=3.9.2 in c:\users\madha\anaconda3\lib\site-packages (from tensorflow) (3.17.2)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\madha\anaconda3\lib\site-packages (from tensorflow) (3.7.4.3)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\madha\anaconda3\lib\site-packages (from tensorflow) (1.36.1)
Requirement already satisfied: wheel<1.0,>=0.32.0 in c:\users\madha\anaconda3\lib\site-packages (from tensorflow) (0.36.2)
Requirement already satisfied: six>=1.12.0 in c:\users\madha\anaconda3\lib\site-packages (from tensorflow) (1.15.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\madha\anaconda3\lib\site-packages (from tensorflow) (1.1.0)
Requirement already satisfied: tensorflow-estimator<2.8,~=2.7.0rc0 in c:\users\madha\anaconda3\lib\site-packages (from tensorflow) (2.7.0)
Requirement already satisfied: tensorboard~=2.6 in c:\users\madha\anaconda3\lib\site-packages (from tensorflow) (2.8.0)
Requirement already satisfied: libclang>=9.0.1 in c:\users\madha\anaconda3\lib\site-packages (from tensorflow) (12.0.0)
Requirement already satisfied: markdown>=2.6.8 in c:\users\madha\anaconda3\lib\site-packages (from tensorboard~=2.6->tensorflow) (3.3.4)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\madha\anaconda3\lib\site-packages (from tensorboard~=2.6->tensorflow) (52.0.0.post20210125)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in c:\users\madha\anaconda3\lib\site-packages (from tensorboard~=2.6->tensorflow) (1.6.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in c:\users\madha\anaconda3\lib\site-packages (from tensorboard~=2.6->tensorflow) (0.4.4)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\madha\anaconda3\lib\site-packages (from tensorboard~=2.6->tensorflow) (2.25.1)
Requirement already satisfied: werkzeug>=0.11.15 in c:\users\madha\anaconda3\lib\site-packages (from tensorboard~=2.6->tensorflow) (1.0.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in c:\users\madha\anaconda3\lib\site-packages (from tensorboard~=2.6->tensorflow) (1.35.0)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in c:\users\madha\anaconda3\lib\site-packages (from tensorboard~=2.6->tensorflow) (0.6.1)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in c:\users\madha\anaconda3\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard~=2.6->tensorflow) (4.2.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\madha\anaconda3\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard~=2.6->tensorflow) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\madha\anaconda3\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard~=2.6->tensorflow) (4.7.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\madha\anaconda3\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.6->tensorflow) (1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\madha\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard~=2.6->tensorflow) (0.4.8)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\madha\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.6->tensorflow) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in c:\users\madha\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.6->tensorflow) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\madha\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.6->tensorflow) (1.26.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\madha\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.6->tensorflow) (2020.12.5)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\madha\anaconda3\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.6->tensorflow) (3.1.1)
Note: you may need to restart the kernel to use updated packages.

pip uninstall tensorflow

In [ ]:
pip install tensorflow

In [ ]:
np.random.seed(1212)
import keras
from keras.models import Model
from keras.layers import *
from keras import optimizers
from keras.layers import Input, Dense
from keras.models import Sequential
from keras.layers import Dropout
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.utils import np_utils

In [10]:
#Df to array
labels = np.array(labels, dtype='int')

In [8]:
labels

array([10, 10, 10, ..., 12, 12, 12])

In [9]:
df_train.head()

,0,1,2,3,4,5,6,7,8,9,...,774,775,776,777,778,779,780,781,782,783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,73,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,255,255,255,255,255,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,18,255,...,0,0,0,0,0,0,0,0,0,0

In [10]:
#categorize labels
from keras.utils.np_utils import to_categorical
cat = to_categorical(labels, num_classes=13)

In [11]:
#total
l = []
for i in range(7101):
    l.append(np.array(df_train[i:i+1]).reshape((28,28,1)))

In [12]:
np.random.seed(7)

In [13]:
model = Sequential()
model.add(Conv2D(30,(5,5), input_shape = (28, 28, 1), activation = "relu"))
model.add(MaxPooling2D(pool_size = (2,2)))
model.add(Conv2D(15,(3,3), activation = "relu"))
model.add(MaxPooling2D(pool_size = (2,2)))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(128, activation = "relu"))
model.add(Dense(50, activation = "relu"))
model.add(Dense(13, activation = "softmax"))

In [14]:
#model compiling
model.compile(loss = "categorical_crossentropy", optimizer = "adam", metrics = ["accuracy"])

pip install tf-nightly

In [16]:
#fitting
model.fit(np.array(l), cat, shuffle = True, epochs = 10)

Epoch 1/10
222/222 [==============================] - 3s 12ms/step - loss: 2.3571 - accuracy: 0.4373
Epoch 2/10
222/222 [==============================] - 4s 17ms/step - loss: 0.6484 - accuracy: 0.7654
Epoch 3/10
222/222 [==============================] - 3s 12ms/step - loss: 0.4453 - accuracy: 0.8254
Epoch 4/10
222/222 [==============================] - 3s 15ms/step - loss: 0.3583 - accuracy: 0.8509
Epoch 5/10
222/222 [==============================] - 3s 15ms/step - loss: 0.3024 - accuracy: 0.8644
Epoch 6/10
222/222 [==============================] - 3s 12ms/step - loss: 0.2643 - accuracy: 0.8740
Epoch 7/10
222/222 [==============================] - 3s 11ms/step - loss: 0.2395 - accuracy: 0.8818
Epoch 8/10
222/222 [==============================] - 2s 11ms/step - loss: 0.2101 - accuracy: 0.8916
Epoch 9/10
222/222 [==============================] - 3s 11ms/step - loss: 0.1979 - accuracy: 0.8930
Epoch 10/10
222/222 [==============================] - 3s 11ms/step - loss: 0.1984 - accuracy: 0.8926

In [ ]:
# Python program to explain cv2.imread() method
  
# importing cv2 
import cv2
  
# path
path = r'C:\Users\madha\Downloads\BE Proj\Dataset\testfinal.jpeg'
  
# Using cv2.imread() method
# Using 0 to read image in grayscale mode
img = cv2.imread(path, 0)
  
# Displaying the image
cv2.imshow('image', img)

In [ ]:

cv2.imshow("w", img)
cv2.waitKey(0) #wait for infinite time
cv2.destroyAllWindows() #destroy prev umages


#test
if img is not None:
    img = ~img
    _, thresh = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY) #remove background and convert image to binary
    ctrs,_ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE) #contours and parent pt; return all boundary points
    cnt = sorted(ctrs, key = lambda ctr:cv2.boundingRect(ctr)[0]) #bounding box/rect
    #for max dimension of rect/block
    w = int(28)
    h = int(28)
    train_data = []
    rects = []
    for c in cnt:
        x, y, w, h = cv2.boundingRect(c)
        rect = [x, y, w, h]
        rects.append(rect)
    print("rects", rects)
    
    
#discard unncessary contours
    bool_rect = []
    for r in rects:
        l = []
        for rec in rects: #finding difference
            flag = 0
            if rec != r:
                if r[0]<(rec[0]+rec[2]+10) and rec[0]<(r[0]+r[2]+10) and r[1]<(rec[1]+rec[3]+10) and rec[1]>(r[1]+r[3]+10):
                           flag = 1
                l.append(flag)
            if rec == r:
                l.append(0)
        bool_rect.append(l)
    print("bools", bool_rect)
    dump_rect = []
    for i in range(0, len(cnt)):
        for j in range(0, len(cnt)):
            if bool_rect[i][j] == i:
                    area1 = rects[i][2]*rects[i][3]
                    area2 = rects[j][2]*rects[j][3]
                    if(area1 == min(area1, area2)):
                           dump_rect.append(rect[i])
    print("dump_rects", dump_rect)
    final_rects = [i for i in rects if i not in dump_rect]
    print("final_rects", final_rects)
    for r in final_rects:
        x = r[0]
        y = r[1]
        w = r[2]
        h = r[3]
        im_crop = thresh[y: y+h+10, x : x+w+10]
        im_resize = cv2.resize(im_crop, (28,28))
        cv2.imshow("work", im_size)
        cv2.waitKey(0)
        cv2.destroyAllWindows()
        train_data.append(im_resize)

In [ ]:
s = ""
for i in range(len(train_data)):
    train_data[i] = np.array((train_data[i]))
    train_data[i] = train_data[i].reshape(1, 28, 28, i)
    result = model.predictclasses(train_data[i])
    if(result[0] == 10):
        s = s + "-"
    if(result[0] == 11):
        s = s + "+"
    if(result[0] == 1):
        s = s + "0"
    if(result[0] == 2):
        s = s + "1"
    if(result[0] == 3):
        s = s + "2"
    if(result[0] == 4):
        s = s + "3"
    if(result[0] == 5):
        s = s + "4"
    if(result[0] == 6):
        s = s + "5"
    if(result[0] == 7):
        s = s + "6"
    if(result[0] == 8):
        s = s + "7"
    if(result[0] == 9):
        s = s + "8"
    if(result[0] == 10):
        s = s + "9"
    if(result[0] == 13):
        s = s + "x"
print(s)